//AUTOGENERATED FILE FROM png2asset
// Conversion args: /chr_gb.png -bpp 2 -tiles_only -keep_duplicate_tiles -sprite_no_optimize -noflip -bin -map -o /chr_gb

#ifndef METASPRITE_chr_gb_H
#define METASPRITE_chr_gb_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define chr_gb_TILE_ORIGIN 0
#define chr_gb_TILE_W 8
#define chr_gb_TILE_H 8
#define chr_gb_WIDTH 128
#define chr_gb_HEIGHT 128
#define chr_gb_TILE_COUNT 256
#define chr_gb_PALETTE_COUNT 3
#define chr_gb_COLORS_PER_PALETTE 4
#define chr_gb_TOTAL_COLORS 12

BANKREF_EXTERN(chr_gb)

extern const palette_color_t chr_gb_palettes[12];
extern const uint8_t chr_gb_tiles[4096];

#endif
