#ifndef POLARGEIST_16HIGH_H
#define POLARGEIST_16HIGH_H

#include <stdint.h>

#define POLARGEIST_16HIGH_WIDTH 934
#define POLARGEIST_16HIGH_HEIGHT 16
#define POLARGEIST_16HIGH_TILE_WIDTH (POLARGEIST_16HIGH_WIDTH * 2)
#define POLARGEIST_16HIGH_TILE_HEIGHT (POLARGEIST_16HIGH_HEIGHT * 2)

extern const uint8_t level_map[];

#endif /* POLARGEIST_16HIGH_H */
