#ifndef COLLISION_H
#define COLLISION_H

#include <stdint.h>

// -------------------------------------------------------
// Collision types — from famidash2gbdk.py / metatiles.inc
// famidash_metatile_collision[tile_id] returns one of these
// -------------------------------------------------------
#define COL_NONE         0x00  // air, pass through
#define COL_DEATH_RIGHT  0x01  // spike facing right  → kills from right
#define COL_DEATH_LEFT   0x02  // spike facing left   → kills from left
#define COL_DEATH_TOP    0x03  // spike facing up     → kills from above
#define COL_DEATH_BOTTOM 0x04  // spike facing down   → kills from below
#define COL_TOP          0x05  // one-way: solid only from above (platform)
#define COL_BOTTOM       0x06  // one-way: solid only from below
#define COL_ALL          0x07  // full solid block, all sides
#define COL_DEATH        0x08  // kills on any contact (orb/sawblade)
#define COL_FLOOR_CEIL   0x09  // solid top and bottom, passthrough sides

// Convenience macros
#define IS_SOLID(col)  ((col) == COL_ALL || (col) == COL_FLOOR_CEIL || \
                        (col) == COL_TOP || (col) == COL_BOTTOM)
#define IS_HAZARD(col) ((col) == COL_DEATH      || \
                        (col) == COL_DEATH_TOP   || \
                        (col) == COL_DEATH_BOTTOM|| \
                        (col) == COL_DEATH_LEFT  || \
                        (col) == COL_DEATH_RIGHT)
#define IS_PASSTHROUGH(col) ((col) == COL_NONE)

// -------------------------------------------------------
// The actual collision table lives in famidash_metatiles.c
// (generated by tools/famidash2gbdk.py from metatiles.inc)
// We just declare it here.
// -------------------------------------------------------
extern const uint8_t famidash_metatile_collision[256];

// Get collision type for a tile ID (safe, clamps at 255)
static inline uint8_t col_of(uint8_t tile_id) {
    return famidash_metatile_collision[tile_id];
}

// Get collision type at a world pixel position
// map: pointer to the 16-row map (rows 11-26 of original)
// map_w: 894, map_h: 16
static inline uint8_t col_at(
    uint16_t world_px,
    int16_t  world_py,
    const uint8_t *map,
    uint16_t map_w,
    uint16_t map_h
) {
    if (world_py < 0) return COL_NONE;            // above map = sky
    uint16_t mx = world_px >> 4;                  // pixel → metatile col
    uint16_t my = (uint16_t)world_py >> 4;        // pixel → metatile row
    if (mx >= map_w || my >= map_h) return COL_ALL; // out of bounds = solid
    return col_of(map[(uint16_t)my * map_w + mx]);
}

#endif // COLLISION_H
